-- In or not out
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INT NOTNULL AUTOINCREMENT PRIMARY KEY,
    email VARCHAR(255) NOTNULL UNIQUE,
    name VARCHAR(255),
    country CHAR(2) NOTNULL DEFAULT 'US' CHECK (country IN ('US', 'CO', 'TN'))
);